name: Build and Push Multi-arch Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to build and push'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: hasura/mcp-connector

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          VERSION: ${{ inputs.version }}
          # Use single platform for faster dev builds, multi-platform for releases
          PLATFORMS: ${{ github.ref == 'refs/heads/main' && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
        run: |
          docker buildx build \
            --platform ${{ env.PLATFORMS }} \
            --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }} \
            --cache-from type=gha \
            --cache-to type=gha,mode=max \
            --push .